### ISSUE TITLE
comment clarification request

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#430]
Tom -- can you clarify what you mean in this comment: 
https://github.com/Applied-GeoSolutions/gips/blob/a2bd9a60a9d384e73404b1c21781e24facd54bfd/gips/data/sentinel2/sentinel2.py#L957

**Comment by ags-tolson** [comment]
I think I believed that doing the arithmetic `T * Ld * scaling_factor` outside of numpy would be faster because I believed (`(rad_rev_img[c] - Lu) / (T * Ld * scaling_factor)`) would result in many repetitions of `T * Ld * scaling_factor`.  I don't remember if I observed it actually going faster in an A/B test, though.
