### ISSUE TITLE
Add end-to-end testing

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#46]
+ set up framework for automated end-to-end testing (akin to the `gips/tests/modis.sh` script) in a standard framework
+ create template for new drivers to implement basic testing of the standard gips features (`gips_process`, `gips_project`, and `gips_inventory`)
+ create testing readme that describes how to run the tests
+ Replace these scripts with tests in the new framework:
  + `modis.sh`
  + `landsat.sh`

**Comment by ags-tolson** [comment]
Work for this lives in `46-sys-tests`.

**Comment by ags-tolson** [comment]
PR issued:  #55

**Comment by ags-tolson** [comment]
(closing since the PR merged; can re-open if needed)

**Comment by ircwaves** [comment]
heh...thought they closed upon merge.  noted.

**Comment by ircwaves** [comment]
Heh...I typed that stuff about converting the `landsat.sh` to pytest, and never hit enter on the comment...so lets open this back up to get the coverage up, and get a ballpark on adding a system test for a "new" datasource/driver.

**Comment by ags-tolson** [comment]
Okay, sounds good.

**Comment by ags-tolson** [comment]
new branch:  https://github.com/Applied-GeoSolutions/gips/tree/46-landsat

**Comment by ags-tolson** [comment]
Essentials are complete; the tests pass in the same pattern as modis.  You can read the tests and expected outputs here:
* https://github.com/Applied-GeoSolutions/gips/blob/46-landsat/gips/test/sys/t_landsat.py
* https://github.com/Applied-GeoSolutions/gips/blob/46-landsat/gips/test/sys/expected/landsat.py
* https://github.com/Applied-GeoSolutions/gips/blob/46-landsat/gips/test/sys/t_repo_src_alteration.py
* https://github.com/Applied-GeoSolutions/gips/blob/46-landsat/gips/test/sys/expected/repo_src_alteration.py

Left to do is looking into atmo correction and seeing if I can do something about performance.  Because landsat is much slower than modis, retaining test inputs differently may be warranted.
