### ISSUE TITLE
CDL NoData value is a valid value?

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#488]
I think that CDL NoData value (zero) is a valid value. So that when an export is done, masked pixels are confused with no-crop pixels. Unless I'm missing something.

**Comment by ircwaves** [comment]
The DBF delivered with CDL data states:
```
Value      : 0
Class name : Background
Red        : 0.00000000000
Green      : 0.00000000000
Blue       : 0.00000000000
Opacity    : 0.00000000000
```
Seems they've opted for setting the opacity to 0 (instead of 1) to indicate NoData.

The CDL classes include many non-crop classes, and zero used to be set as the no-data value (see #38). They have stopped setting that metadata item, however, I believe "Background" means unclassified, not "no crop".  Also could have misunderstood something here, but I believe we've hashed this one out.

**Comment by bhbraswell** [comment]
got it. THANKS
