### ISSUE TITLE
Problem specifying tile for download without site shapefile or raster mask

### ISSUE THREAD

**Issue by sullamenashe** [Applied-GeoSolutions/gips#497]
This command doesnt work:
`gips_export sentinel2 --fetch -p ref-toa -d 2018-08-01 --outdir /mnt/storage --notld -t 15TUH`

It gives the error: error: one of the arguments -s/--site -r/--rastermask is required

When adding the -s flag like below, the command does work: 
`gips_export sentinel2 --fetch -p ref-toa -d 2018-08-01 --outdir /mnt/storage --notld -t 15TUH -s conf-gips/vector/test_tile.shp`

Is this a known issue or a bug?

**Comment by ircwaves** [comment]
I think this goes under known issue.  Export is for mosaicking and clipping imagery to a supplied geometry's extent (`-s` or `-r`).  There is an unmaintained script (`gips_tiles`) which was intended to copy tiles out of the archive.  It's been years since I touched it.

Without `--res` supplied, GIPS attempts to `gdal_merge` the source imagery, and can blow up if the source imagery have different projections.  I think this highlights that we might want to make `--res` also a required argument for export.  Though there may be some edge case where one does want the sensitive behaviour of a non-`--res` export. 

Specification of `--res` in implicit-units that don't match the units of the vector is problematic.  For example, `-s my_geographic_projection_geom.shp --res 500 500` (user likely assumes meters) will attempt to generate output that has 500 degree by 500 degree pixels.
