### ISSUE TITLE
gips_stats L8

### ISSUE THREAD

**Issue by mcorbiere** [Applied-GeoSolutions/gips#7]
gips_stats on project directories that have L8 + L(5 or 7) produces text files with faulty headers.

**Comment by ircwaves** [comment]
from our off-line conversation, this is only an issue for `gips_stats` when a product has different sets of bands (ref, rad) for different sensors.   A solution would be to gather all the stats in a dictionary by bands before writing it out to a table, rather than writing on while gathering stats.  Might actually be faster that way too.

**Comment by ircwaves** [comment]
@mcorbiere can you post an example of a problem file to jog my memory?

**Comment by mcorbiere** [comment]
I don't have any actual examples at the moment (I can add one later), but here's what it does:

Landsat 7 ref bands: BLUE, GREEN, RED, NIR, SWIR (i think)
Landsat 8 ref bands: Coastal, BLUE, GREEN RED, ... Cirrus

So if you have landsat 7 and 8 in the same directory and you run gips_stats, it puts them both in the same .txt file, but doesn't know what to do with the different headers. So I believe the output was that there would not be any headers for the extra landsat 8 bands.

**Comment by bhbraswell** [comment]
Can we make it get descriptive names form the appropriate driver class?

**Comment by ircwaves** [comment]
Since `gips_stats` works on the project directory level and there isn't a unique mapping from gips_project files to `gips.data` drivers, it isn't possible at the moment.

We probably should push that info into the metadata of each TIFF (for data provenance purposes) and then at that point we could grab that info.

**Comment by ircwaves** [comment]
@remeryAGS -- does spatial aggregator address the OP concerns?  I feel like we addressed this in the initial work on it, but it has been a while, and we haven't written a test for it yet.

**Comment by ircwaves** [comment]
I'll go ahead and state that SpatialAggregator does address these concerns.
